### ISSUE TITLE
Add libs to final zip

### ISSUE THREAD

**Issue by tangrammer** [mrmcc3/lein-zip#2]
Hi @mrmcc3 and thanks for sharing this!
I needed to add folders to final zip compilation and i reached to this code, 
https://github.com/tangrammer/lein-zip/commit/472f7e9fcb598fc87c4734b73b718861efcc7150
let me know if you want to merge (or improve it) with your lib and I'll send you a PR 
have a good day!
Juan

**Comment by mrmcc3** [comment]
@tangrammer this should work now. Thank you

**Comment by tangrammer** [comment]
Thanks!

**Comment by tangrammer** [comment]
Could you deploy to clojars this update?

**Comment by mrmcc3** [comment]
https://clojars.org/lein-zip/versions/0.1.1
